name: "Release on npm owon"
on:
  push:
    branches:
      - main

jobs:
  release:
    name: npm-publish
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org
        package-manager-cache: false
    - run: npm ci
    - run: npm run dist
    - run: npm run dev
    - run: npm test
    - run: npm publish --access public
